#!/usr/bin/env bash

curl 'https://localhost:7240/graphql' \
  -X 'POST' \
  -H 'Content-Type: application/json' \
  -H 'Pragma: no-cache' \
  -H 'Accept: */*, application/json' \
  -H 'Accept-Language: en-CA,en-US;q=0.9,en;q=0.8' \
  -H 'Accept-Encoding: gzip, deflate, br' \
  -H 'Cache-Control: no-cache' \
  -H 'Host: localhost:7240' \
  -H 'Origin: https://localhost:7240' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.2 Safari/605.1.15' \
  -H 'Connection: keep-alive' \
  -H 'Referer: https://localhost:7240/ui/playground' \
  -H 'Content-Length: 240' \
  --data-binary '{"operationName":null,"variables":{},"query":"{\n  getYearlyCashFlow(year: 2020) {\n    startAt\n    endAt\n    creditListings {\n      tags {\n        name\n      }\n      amount\n    }\n    debitListings {\n      amount\n    }\n  }\n}\n"}';
